In [2]:
import numpy as np

## Datatype

In [5]:
# np main datatype is ndarray - n dimensional array
a1 =  np.array([1, 2, 3])
type(a1)

numpy.ndarray

In [9]:
a2 = np.array([[1, 2, 3], [4, 5, 6]])

a3 = np.array([[[1, 2, 3], [4, 5, 6], [7, 8, 9], [10, 11, 12], [13, 14, 15]]])
a3

array([[[ 1,  2,  3],
        [ 4,  5,  6],
        [ 7,  8,  9],
        [10, 11, 12],
        [13, 14, 15]]])

In [19]:
print(f"shape: {a1.shape}")
print(f"ndim: (number of dimensions): {a1.ndim}")
print(f"dtype: {a1.dtype}")
print(f"size: {a1.size}")
print(f"type: {type(a1)}")

shape: (3,)
ndim: (number of dimensions): 1
dtype: int64
size: 3
type: <class 'numpy.ndarray'>


## Creating arrays

In [23]:
sample_array = np.array([1, 2, 3])
sample_array # 1 dimensional array

array([1, 2, 3])

In [33]:
ones = np.ones((2, 3)) ## creates an array filled with 1
print(ones)

print()

zeros = np.zeros((3, 4))
print(zeros)

[[1. 1. 1.]
 [1. 1. 1.]]

[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]


In [35]:
# np.arange(<start>, <stop>, <step>)
range_array = np.arange(0, 10, 2)
print(range_array)

[0 2 4 6 8]


In [44]:
random_array = np.random.random((2, 3))
print(random_array)

[[0.96553472 0.70290561 0.45283699]
 [0.06218556 0.42588187 0.80958153]]


In [59]:
random_array_3 = np.random.rand(5, 3)
print(random_array)

[[0.96553472 0.70290561 0.45283699]
 [0.06218556 0.42588187 0.80958153]]


In [62]:
## Pseudo-random numbers ???
np.random.seed(0)

random_array_4 =  np.random.randint(10, size=(5, 3))
print(random_array_4)

[[5 0 3]
 [3 7 9]
 [3 5 2]
 [4 7 6]
 [8 8 1]]


## Viewing Arrays and Matrices

In [73]:
print(a2, "\n")
print(a2[0], "\n")
print(a2[0][2], "\n")

[[1 2 3]
 [4 5 6]] 

[1 2 3] 

3 



In [77]:
a2[:1, :2]

array([[1, 2]])

In [84]:
a4 = np.random.randint(10, size=(4, 3, 5, 4))
print(a4, "\n")

print(a4[:2, :2, :2, :2])

[[[[5 8 4 0]
   [2 5 5 0]
   [8 1 1 0]
   [3 8 8 4]
   [4 0 9 3]]

  [[7 3 2 1]
   [1 2 1 4]
   [2 5 5 5]
   [2 5 7 7]
   [6 1 6 7]]

  [[2 3 1 9]
   [5 9 9 2]
   [0 9 1 9]
   [0 6 0 4]
   [8 4 3 3]]]


 [[[8 8 7 0]
   [3 8 7 7]
   [1 8 4 7]
   [0 4 9 0]
   [6 4 2 4]]

  [[6 3 3 7]
   [8 5 0 8]
   [5 4 7 4]
   [1 3 3 9]
   [2 5 2 3]]

  [[5 7 2 7]
   [1 6 5 0]
   [0 3 1 9]
   [9 6 6 7]
   [8 8 7 0]]]


 [[[8 6 8 9]
   [8 3 6 1]
   [7 4 9 2]
   [0 8 2 7]
   [8 4 4 1]]

  [[7 6 9 4]
   [1 5 9 7]
   [1 3 5 7]
   [3 6 6 7]
   [9 1 9 6]]

  [[0 3 8 4]
   [1 4 5 0]
   [3 1 4 4]
   [4 0 0 8]
   [4 6 9 3]]]


 [[[3 2 1 2]
   [1 3 4 1]
   [1 0 7 8]
   [4 3 5 6]
   [3 2 9 8]]

  [[1 4 0 8]
   [3 9 5 5]
   [1 7 8 6]
   [4 7 3 5]
   [3 6 4 7]]

  [[3 0 5 9]
   [3 7 5 5]
   [8 0 8 3]
   [6 9 3 2]
   [7 0 3 0]]]] 

[[[[5 8]
   [2 5]]

  [[7 3]
   [1 2]]]


 [[[8 8]
   [3 8]]

  [[6 3]
   [8 5]]]]
